public enum SocketPostmanTaskTypeList {
    READ_SYMBOL_ARRAY_BOOMERANG_SLAVE,
    READ_SYMBOL_ARRAY_BOOMERANG_MASTER,
    READ_SYMBOL_ARRAY,
    READ_BYTE_ARRAY_BOOMERANG_SLAVE,
    READ_BYTE_ARRAY_BOOMERANG_MASTER,
    READ_BYTE_ARRAY
}
